ExcellOn.PL/Areas/Admin/Controllers/ServiceController.cs
using ExcellOn.BLL;
using ExcellOn.PL.Areas.Admin.Filter;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using ExcellOn.DAL;
using ExcellOn.PL.Areas.Admin.Helper;
using System.Net;
using ExcellOn.PL.Areas.Admin.Helper.AuthorizeHelper;

namespace ExcellOn.PL.Areas.Admin.Controllers
{
    [CustomAuthorize]
    public class ServiceController : Controller
    {


        // GET: Admin/Service
        private Repository<DAL.Service> servivceR;
        private Repository<OrderDetail> orderdetails;
        public ServiceController()
        {
            servivceR = new Repository<DAL.Service>();
            orderdetails = new Repository<OrderDetail>();
        }
        public ActionResult Index()
        {
            ViewBag.activeService = "active";
            ViewBag.show = "show";
            return View();
        }
        [HttpPut]
        public ActionResult UpdateStatus(int id)
        {
            var infor = servivceR.FindOneById(id);

            if (infor != null)
            {
                infor.Status = !infor.Status;
                servivceR.SaveEdit();
                return Json(new
                {
                    type = "success",
                    message = "Successfully "

                }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new
                {
                    type = "error",
                    message = "Error "

                }, JsonRequestBehavior.AllowGet);
            }
        }
        
        public ActionResult GetAll(int page = 1, string search = "")
        {
            var data = servivceR.FindAll();

            if (!string.IsNullOrEmpty(search))
            {
                data = data.Where(x => (x.Name.ToLower().Contains(search.ToLower())) || (x.Description.ToLower().Contains(search.ToLower()))).ToList();
            }

            foreach (var item in data)
            {
                item.IdEncrypt = Encrypt.EncryptString(item.Id.ToString());
            }
            var pageSize = 5;

            int totalPage = (int)Math.Ceiling((double)data.Count() / pageSize);
            return Json(new
            {
                statusCode = 200,
                page = page,
                search = search,
                totalPage = totalPage,
                pageSize = pageSize,
                data = data.Skip((page - 1) * pageSize).Take(pageSize).OrderBy(x => x.Name)
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetOne(string IdEncrypt)
        {
            try
            {
                var Id = Convert.ToInt32(Encrypt.DecryptString(IdEncrypt));
                var service = servivceR.FindOneById(Id);

                return Json(new
                {
                    statusCode = 200,
                    data = service,

                }, JsonRequestBehavior.AllowGet);


            }
            catch (Exception)
            {

                return Json(new
                {
                    statusCode = 200,
                    type = "error",
                    message = "The system is busy, please reload the page !",

                }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        [ModelValidation]
        public ActionResult Save(DAL.Service entity)
        {
            var type = "";
            var message = "";
            Dictionary<string, string> errors = new Dictionary<string, string>();
            entity.Status = true;
            try
            {
                entity.Image = FileHelper.UploadedFile(entity.PostedFileBase);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("PostedFileBase", ex.Message);
            }

            if (ModelState.IsValid)
            {
                try
                {

                    servivceR.Add(entity);
                    type = "success";
                    message = "Successfully";
                }
                catch (Exception e)
                {

                    type = "error";
                    message = e.Message;

                }

            }
            else
            {

                foreach (var k in ModelState.Keys)
                {
                    foreach (var err in ModelState[k].Errors)
                    {
                        string key = Regex.Replace(k, @"(\w+)\.(\w+)", @"$2");
                        if (!errors.ContainsKey(key))
                        {
                            errors.Add(key, err.ErrorMessage);
                        }
                    }
                }
            }

            return Json(new
            {
                statusCode = HttpStatusCode.OK,

                type = type,
                message = message,
                errors = errors.Count() > 0 ? errors : null
            }, JsonRequestBehavior.AllowGet); ;
        }

        [HttpPut]
        public ActionResult Edit(DAL.Service entity)
        {
            var type = "";
            var message = "";
            Dictionary<string, string> errors = new Dictionary<string, string>();
            if (entity.PostedFileBase != null && entity.PostedFileBase.ContentLength > 0)
            {
                try
                {
                    entity.Image = FileHelper.UploadedFile(entity.PostedFileBase);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("PostedFileBase", ex.Message);
                }
            }
            else
            {
                entity.Image = servivceR.FindOneByExpressToEdit(x => x.Id == entity.Id).Image;
            }
            if (ModelState.IsValid)
            {
                try
                {
                    servivceR.Edit(entity);
                    type = "success";
                    message = "Successfully";
                }
                catch (Exception e)
                {

                    type = "error";
                    message = e.Message;
                }

            }

            foreach (var k in ModelState.Keys)
            {
                foreach (var err in ModelState[k].Errors)
                {
                    string key = Regex.Replace(k, @"(\w+)\.(\w+)", @"$2");
                    if (!errors.ContainsKey(key))
                    {
                        errors.Add(key, err.ErrorMessage);
                    }
                }
            }

            return Json(new
            {
                statusCode = 200,

                type = type,
                message = message,
                errors = errors.Count() > 0 ? errors : null
            }, JsonRequestBehavior.AllowGet);
        }
        [HttpDelete]
        public ActionResult Delete(string IdEncrypt)
        {
            try
            {
                var Id = Convert.ToInt32(Encrypt.DecryptString(IdEncrypt));
                if (orderdetails.Any(x=>x.ServiceId==Id))
                {
                    return Json(new
                    {
                        status = 200,
                        type = "error",
                        message = "Can't delete this service "

                    }, JsonRequestBehavior.AllowGet); ;
                }
                else
                {
                    servivceR.Delete(Id);

                    return Json(new
                    {
                        status = 200,
                        type = "success",
                        message = "Delete successfully ",

                    }, JsonRequestBehavior.AllowGet);
                }
                
            }
            catch (Exception e)
            {
                return Json(new
                {
                    status = 200,
                    type = "error",
                    message = e.Message

                }, JsonRequestBehavior.AllowGet); ;

            }
        }

        public ActionResult Detail(string Id)
        {
            try
            {
                var serviceId = Convert.ToInt32(Encrypt.DecryptString(Id));
                var service = servivceR.FindOneById(serviceId);
                service.IdEncrypt = Id;
                ViewBag.activeService = "active";
                ViewBag.show = "show";
                return View(service);


            }
            catch (Exception)
            {

                return RedirectToAction("Index");
            }

        }
    }
}

ExcellOn.PL/Controllers/ServiceController.cs
using ExcellOn.BLL;
using ExcellOn.DAL;
using ExcellOn.PL.Areas.Admin.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExcellOn.PL.Controllers
{
    public class ServiceController : Controller
    {
        // GET: Service
        private Repository<DAL.Service> serviceR;
        private Repository<ServiceReview> reviewR;
        private Repository<User> userRepo;
        private IRepository<FavoriteService> favoriteService;
        public ServiceController()
        {
            serviceR = new Repository<DAL.Service>();
            reviewR = new Repository<ServiceReview>();
            userRepo = new Repository<User>();
            favoriteService = new Repository<FavoriteService>();
        }

        public ActionResult Index(string search="")
        {
            var data = serviceR.FindAllByExpress(x=>x.Status);
            if (!String.IsNullOrEmpty(search))
            {
                data = data.Where(x => x.Name.ToLower().Contains(search.ToLower()) || x.ShortDescription.ToLower().Contains(search.ToLower()));
            }
            foreach (var item in data)
            {
                item.IdEncrypt = Encrypt.EncryptString(item.Id.ToString());
            }
            return View(data);
        }
        public ActionResult ServiceDetail(string id)
        {
            try
            {
                var serviceId = Convert.ToInt32(Encrypt.DecryptString(id));

                var email = HttpContext.Request.Cookies["email"] == null ? "" : HttpContext.Request.Cookies["email"].Value;
                var user = userRepo.FindOneByExpress(x => x.Email.Equals(email));

                var listReview = reviewR.FindAllByExpress(x => x.Status != 0 && x.ServiceId == serviceId);
                var countReview = listReview.Count();
                double countRate = 0;
                double count = 0;

                var review = reviewR.FindAllByExpress(x => x.ServiceId == serviceId);
                foreach (var item in review)
                {
                    count++;
                    countRate += item.Rate;
                }
                double mediumrate = countRate / count;
                ViewBag.mediumrate = mediumrate;

                var listService = serviceR.FindAllByExpress(x=>x.Id!=serviceId);
                var data = serviceR.FindOneById(serviceId);
                if (user != null)
                {
                    foreach (var item in listService)
                    {
                        item.IdEncrypt = Encrypt.EncryptString(item.Id.ToString());
                        if (favoriteService.Any(x => x.UserId == user.Id && x.ServiceId == item.Id))
                        {
                            item.IsFavorite = true;
                        }
                    }

                    if (favoriteService.Any(x => x.UserId == user.Id && x.ServiceId == data.Id))
                    {
                        data.IsFavorite = true;
                    }
                }
                ViewBag.listService = listService;
                ViewBag.listReview = listReview;
                ViewBag.coureview = countReview;
                return View(data);

            }
            catch (Exception)
            {

                return RedirectToAction("Index");
            }
            
        }
    }
}

ExcellOn.PL/Views/Service/Index.cshtml
@model IEnumerable<ExcellOn.DAL.Service>
@{
    ViewBag.Title = "Service ";
    Layout = "~/Views/Shared/_LayoutPage2.cshtml";
}

<div class="page-banner-area">
    <div class="container">
        <div class="page-banner-content">
            <h2>Services </h2>
            <ul>
                <li>
                    <a href="@Url.Action("Index","Home")">Home</a>
                </li>
                <li>Services </li>
            </ul>
        </div>
    </div>
    <div class="page-banner-shape-1" data-speed="0.08"
         data-revert="true">
        <img src="~/Content/assets/images/page-banner/shape-1.png" alt="image">
    </div>
    <div class="page-banner-shape-2" data-speed="0.08"
         data-revert="true">
        <img src="~/Content/assets/images/page-banner/shape-2.png" alt="image">
    </div>
    <div class="page-banner-shape-3" data-speed="0.08"
         data-revert="true">
        <img src="~/Content/assets/images/page-banner/shape-3.png" alt="image">
    </div>
    <div class="page-banner-shape-4" data-speed="0.08"
         data-revert="true">
        <img src="~/Content/assets/images/page-banner/shape-4.png" alt="image">
    </div>
</div>


<div class="services-area pt-100 pb-70">
    <div class="container">
        <div class="row justify-content-center">
            @foreach (var item in Model)
            {
            <div class="col-lg-4 col-md-6">
                
                <div class="single-services-item">
                    <div class="icon bg-FF6D3D">
                        <i class="ri-customer-service-2-line"></i>
                    </div>
                    <h4>
                        
                        <a href="@Url.Action("ServiceDetail","Service",new { id= item.IdEncrypt})"> @item.Name</a>

                    </h4>
                    <p class="short-decription">

                        @{

                            string sortDecription = item.ShortDescription;

                            if (sortDecription != null && sortDecription.Length > 200) { sortDecription = sortDecription.Substring(0, 200) +"..."; }



                        }
                        @sortDecription
                    </p>
                    <a href="@Url.Action("ServiceDetail","Service",new { id= item.IdEncrypt})" class="btn services-btn">
                       
                        Read More <i class="ri-arrow-right-line"></i>
                    </a>
                </div>
            </div>
            }


        </div>
    </div>
    <div class="services-shape-1" data-speed="0.06" data-revert="true">
        <img src="~/Content/assets/images/services/shape-1.png" alt="image">
    </div>
    <div class="services-shape-2" data-speed="0.06" data-revert="true">
        <img src="~/Content/assets/images/services/shape-2.png" alt="image">
    </div>
    <div class="services-shape-3" data-speed="0.06" data-revert="true">
        <img src="~/Content/assets/images/services/shape-3.png" alt="image">
    </div>
    <div class="services-shape-4" data-speed="0.06" data-revert="true">
        <img src="~/Content/assets/images/services/shape-4.png" alt="image">
    </div>
    <div class="services-shape-5" data-speed="0.06" data-revert="true">
        <img src="~/Content/assets/images/services/shape-5.png" alt="image">
    </div>
</div>


<div class="process-area pb-100">
    <div class="container">
        <div class="process-inner-box">
            <div class="row">
                <div class="col-lg-3 col-sm-6">
                    <div class="single-process">
                        <i class="ri-hard-drive-line"></i>
                        <p>Research</p>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="single-process bg-36CC72">
                        <i class="ri-pie-chart-line"></i>
                        <p>Analyze</p>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="single-process bg-FF414B">
                        <i class="ri-quill-pen-line"></i>
                        <p>Design</p>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="single-process bg-FF6D3D">
                        <i class="ri-focus-line"></i>
                        <p>Testing</p>
                    </div>
                </div>
            </div>
            <div class="process-bar-shape">
                <img src="~/Content/assets/images/process-bar.png" alt="image">
            </div>
        </div>
    </div>
</div>


<div class="support-area">
    <div class="container">
        <div class="support-content">
            <div class="tag">
                <img src="~/Content/assets/images/experiences/tag-icon.png"
                     alt="image">
            </div>
            <h3>Lightning-Fast Tech Support, Guaranteed</h3>
            <p>
                As a midsize software development company, we combine the
                best of both worlds. We have the focus and speed of the
                small IT outsourcing companies along with the
                scalability and expertise of the big ones.
            </p>
            <span>Regan Rosen, CEO at Flod Agency</span>
        </div>
    </div>
    <div class="support-shape-1" data-speed="0.08" data-revert="true">
        <img src="~/Content/assets/images/support/shape-1.png" alt="image">
    </div>
    <div class="support-shape-2" data-speed="0.08" data-revert="true">
        <img src="~/Content/assets/images/support/shape-2.png" alt="image">
    </div>
    <div class="support-shape-3" data-speed="0.08" data-revert="true">
        <img src="~/Content/assets/images/support/shape-3.png" alt="image">
    </div>
    <div class="support-shape-4" data-speed="0.08" data-revert="true">
        <img src="~/Content/assets/images/support/shape-4.png" alt="image">
    </div>
    <div class="support-shape-5" data-speed="0.08" data-revert="true">
        <img src="~/Content/assets/images/support/shape-5.png" alt="image">
    </div>
    <div class="support-shape-6" data-speed="0.02" data-revert="true">
        <img src="~/Content/assets/images/support/shape-6.png" alt="image">
    </div>
</div>

ExcellOn.PL/Views/Service/ServiceDetail.cshtml
@model ExcellOn.DAL.Service
@{
    ViewBag.Title = "Service Details";
    Layout = "~/Views/Shared/_LayoutPage2.cshtml";
}
@section css{
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <link href="~/Content/assets/css/favorite.css" rel="stylesheet" />
    <style>
        .rate {
            font-size: 35px;
            color: orange;
        }
    </style>
}

<div class="page-banner-area">
    <div class="container">
        <div class="page-banner-content">
            <h2>Service Details</h2>
            <ul>
                <li>
                    <a href="@Url.Action("Index","home")">Home</a>
                </li>
                <li>Service Details</li>
            </ul>
        </div>
    </div>
    <div class="page-banner-shape-1" data-speed="0.08" data-revert="true">
        <img src="~/Content/assets/images/page-banner/shape-1.png" alt="image">
    </div>
    <div class="page-banner-shape-2" data-speed="0.08" data-revert="true">
        <img src="~/Content/assets/images/page-banner/shape-2.png" alt="image">
    </div>
    <div class="page-banner-shape-3" data-speed="0.08" data-revert="true">
        <img src="~/Content/assets/images/page-banner/shape-3.png" alt="image">
    </div>
    <div class="page-banner-shape-4" data-speed="0.08" data-revert="true">
        <img src="~/Content/assets/images/page-banner/shape-4.png" alt="image">
    </div>
</div>


<div class="products-details-area ptb-100">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-5 col-md-12 services-details-overview-content">
                <div class="overview-image">
                    <img src="~/Areas/Admin/Content/Images/@Model.Image"
                         alt="image">

                </div>
            </div>
            <div class="col-lg-7 col-md-12">
                <div class="products-details-desc">
                    <h3 style="margin-bottom:0">@Model.Name</h3>
                    <div class="products-review">
                        <div class="rating" style="display:flex">
                            <div class="rate" data-rate-value="@ViewBag.mediumrate"></div>
                            <a href="#" class="rating-count" style="height:30px;margin-top:22px">(@ViewBag.mediumrate Rates)</a>
                        </div>
                    </div>
                    <div class="price">
                        @String.Format("{0:C}", Model.Change)  (per day per employee)
                    </div>
                    <p>
                        @Model.ShortDescription
                    </p>
                    <div class="products-share">
                        <ul class="social">
                            <li><span>Share:</span></li>
                            <li><a href="#" target="_blank"><i class="ri-facebook-fill"></i></a></li>
                            <li><a href="#" target="_blank"><i class="ri-twitter-fill"></i></a></li>
                            <li><a href="#" target="_blank"><i class="ri-linkedin-fill"></i></a></li>
                            <li><a href="#" target="_blank"><i class="ri-instagram-fill"></i></a></li>
                        </ul>
                    </div>
                    <div class="products-add-to-cart">

                        @{
                            var color = Model.IsFavorite ? "red" : "#5A5858";
                        }


                        <button type="button" class="btn btn-outline-success btn-add" style="margin-right:10px;margin-bottom:28px;">Use Service<span></span></button>
                        <i class="fa fa-heart add-wishlist" data-id="@Model.Id" aria-hidden="true" style="font-size: 3em;cursor:pointer; color:@color"></i>

                        @*<svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="red" cursor="pointer" class="bi bi-heart add-wishlist" viewBox="0 0 16 16" data-id="@Model.Id">
                                <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"></path>
                            </svg>*@

                    </div>

                </div>
            </div>
            <div class="col-lg-12 col-md-12">
                <div class="products-details-tabs">
                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        <li class="nav-item"><a class="nav-link active" id="description-tab" data-bs-toggle="tab" href="#description" role="tab" aria-controls="description">Description</a></li>
                        <li class="nav-item"><a class="nav-link" id="reviews-tab" data-bs-toggle="tab" href="#reviews" role="tab" aria-controls="reviews">Reviews (@ViewBag.coureview)</a></li>
                    </ul>
                    <div class="tab-content" id="myTabContent">
                        <div class="tab-pane fade show active" id="description" role="tabpanel">
                            @Html.Raw(Model.Description)
                        </div>
                        <div class="tab-pane fade" id="reviews" role="tabpanel">
                            <div class="products-review-comments">
                             
                                @foreach (var item2 in ViewBag.listReview)
                                {
                                    <div class="user-review">
                                        @{
                                            var avatar = "/Areas/Admin/Content/Images/" + item2.User.Avatar;
                                            if (String.IsNullOrEmpty(item2.User.Avatar))
                                            {
                                                avatar = "https://ui-avatars.com/api/?name=" + item2.User.Name;
                                            }
                                        }

                                        <img src="@avatar" />
                                        <div class="review-rating">
                                            <div class="rate" data-rate-value="@item2.Rate" style="font-size:35px;"></div>
                                            <span class="d-inline-block">@item2.User.Name</span>
                                        </div>
                                       
                                        <p>@item2.Comment</p>
                                    </div>
                                }

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="product-area pb-70">
    <div class="container">
        <div class="section-title">
            <h2>Other services</h2>
        </div>
        <div class="row">
            @foreach (var item in ViewBag.listService)
            {
                <div class="col-lg-6 col-sm-6">
                    <div class="single-products-box">
                        <div class="products-image overview-image">
                            <a href="@Url.Action("ServiceDetail","Service",new { id= item.IdEncrypt})">
                                <img src="~/Areas/Admin/Content/Images/@item.Image" alt="image" style="height:250px;">
                            </a>
                            @{
                                var Iswishlist = item.IsFavorite ? "red" : "#5A5858";
                            }
                            <div class="action">
                                <a href="javascript:void(0)" class="btn-add-cartItem-fast" data-serviceId="@item.Id"><i class="ri-shopping-cart-line"></i></a>
                                <a href="javascript:void(0)"> <i class="fa fa-heart add-wishlist" data-id="@item.Id" aria-hidden="true" style="cursor:pointer; color:@Iswishlist"></i></a>
                            </div>
                        </div>
                        <div class="products-content">
                            <h3><a href="@Url.Action("ServiceDetail","Service",new { id= item.IdEncrypt})">@item.Name ( @String.Format("{0:C}", item.Change))</a></h3>
                           
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<div class="modal fade" id="modal-add-service" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <form id="form-add-service">
            <div class="modal-content">
               
                <div class="modal-body">

                    <input type="hidden" value="@Model.Id" id="ServiceId" name="ServiceId" />
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Date Number</label>
                        <input type="text" class="form-control" id="DateNumber" name="DateNumber" value="1">
                    </div>
                    <div class="form-group">
                        <label for="message-text" class="col-form-label">Employee Number</label>
                        <input type="text" class="form-control" id="EmployeeNumber" name="EmployeeNumber" value="1">
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-6">
                                <label for="message-text" class="col-form-label">Changes</label>
                                <input type="text" class="form-control" id="Changes" name="Changes" value="@Model.Change" disabled>
                            </div>
                            <div class="col-md-6">
                                <label for="message-text" class="col-form-label">Total Price</label>
                                <input type="text" class="form-control" id="TotalPrice" name="TotalPrice" value="@Model.Change" disabled>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-danger " id="close-modal" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-outline-info btn-add-cartItem ">Add to Cart</button>
                </div>
            </div>
        </form>
    </div>
</div>
@section scripts{
    <script src="~/Content/assets/js/rater.min.js"></script>
    <script src="~/Areas/Admin/Content/bootstrap/js/validate.min.js"></script>
    <script src="~/Content/assets/Ajax/ajax-service-detail.js"></script>
    <script>
        $(document).ready(function () {
            var options = {
                max_value: 5,
                step_size: 0.1,
            }
            $(".rate").rate(options);
        });
    </script>
}